### ISSUE TITLE
Nytt design og funksjonalitet på NiN-Kart

### ISSUE THREAD

**Issue by helemork** [Artsdatabanken/nin-kart-frontend#1381]
### FØR DENNE LASTES OPP:

- #1394 
- #1268 
- #1293 
- BRUKERTEST LITT MED FOLK
- SJEKK AT TING FUNKER

## To-DO for @bjornreppen 

- [x] datakilde knapp går til undefined
resten flyttet til egne issues, du er lenket opp. Fokuser KUN på den som det står critical på (#1394)

## To-DO generelt

- [x] Splitte i to hovedfunksjoner : Info og Kartlag

### Layout

- [x] plassering av underobjektene som klikkbare små underelement med bilder på 
- [x] Endre topbar til mer snasen look som følger uu bedre

### Navigeringsmeny
- [x] Hierarki opp og ned i samme meny, med nåværende element i midten, deaktivert
- [x] Få på plass tab-struktur
- [x] Max laste inn 10 element om gangen nedover i listen med en vis fler-knapp

### Endring i kartlag
- [x] Legg til slider-elementene (rgadient-filter) også for nåværende kartlag
- [x]  Scrollbar-bug på mobil (tror fikset)

### Mobil:
- [x] tre hovedfaner, Meny, Info, Kart
- [x] Slå sammen kartlg og kart til én fane, men la kartlag være en slide-up som viser ét element når nede, og hele menyen når åpen
- [x] Automatisk åpne nåværende menyen så legenden er tilgjengelig
- [x] kun vide de 5 øverste fanene, lag vis mer-knapp for å utvide til fler element
- [x] endre øvre bit av kartlag til transparent knapp så man kan trykke på

### Endring i lokasjon
- [x] få inn lokasjon i navigasjonstreet, forankret under rktig fylke/kommune
- [x] la den se ut som informasjons-side

# Bakgrunn for endring
Etter en del møter, prototyping og diverse, kom vi frem til å lage en ny og bedre variant av siden, med en det sammenslåing og omplassering av funksjoner og elementer.

Vil fikse mange universell utforming-krav!

fixes #1299 
fixes #1206 
closes #1287 som ikke lengre er relevant
fixes #1268 (forhåpentligvis) <-- bedreinnhold for utenfor landegrenser, vil ordnes om man ikke går dit pga at man ikke får opp noe, og derav ingen lenke
closes #1112 ikke lengre relevant
closes #1209, siden det ble bestemt å gjøre det med tab 
fixes #1362

Legger ved de første skissene. De er litt gått bort i fra på dette tidspunktet.

![1](https://user-images.githubusercontent.com/17450081/60437507-cdef5480-9c0e-11e9-950f-c13d8fc2764f.jpg)
![2](https://user-images.githubusercontent.com/17450081/60437510-cfb91800-9c0e-11e9-8c97-c6e344c2274d.jpg)
